/turtle_controller:
  ros__parameters:
    catch_closest_turtle_first: true  # Use lowercase 'true' (YAML standard)

/turtle_spawner:
  ros__parameters:
    turtle_name_prefix: "my_turtle"
    spawn_frequency: 1.0  # Correct usage of float value
